"""initial store schema

Revision ID: 2e59398fc13d
Revises: 
Create Date: 2026-06-29 17:02:45.334302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e59398fc13d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='store'
    )
    op.create_index(op.f('ix_store_categories_slug'), 'categories', ['slug'], unique=True, schema='store')
    op.create_table('customers',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.Enum('active', 'inactive', 'suspended', 'deleted', name='account_status'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_customers_email'), 'customers', ['email'], unique=True, schema='store')
    op.create_table('carts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_carts_customer_id'), 'carts', ['customer_id'], unique=True, schema='store')
    op.create_table('customer_addresses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False, schema='store')
    op.create_table('orders',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('shipping_name', sa.String(length=150), nullable=False),
    sa.Column('shipping_phone', sa.String(length=20), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount >= 0', name='ck_order_discount_positive'),
    sa.CheckConstraint('shipping_cost >= 0', name='ck_order_shipping_cost_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_order_subtotal_positive'),
    sa.CheckConstraint('tax >= 0', name='ck_order_tax_positive'),
    sa.CheckConstraint('total_amount >= 0', name='ck_order_total_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_orders_customer_id'), 'orders', ['customer_id'], unique=False, schema='store')
    op.create_index(op.f('ix_store_orders_public_id'), 'orders', ['public_id'], unique=True, schema='store')
    op.create_table('phone_numbers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_phone_numbers_customer_id'), 'phone_numbers', ['customer_id'], unique=False, schema='store')
    op.create_table('products',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_price IS NULL OR discount_price <= price', name='ck_product_discount_price'),
    sa.CheckConstraint('price > 0', name='ck_product_price_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['store.categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_products_category_id'), 'products', ['category_id'], unique=False, schema='store')
    op.create_index(op.f('ix_store_products_name'), 'products', ['name'], unique=False, schema='store')
    op.create_index(op.f('ix_store_products_slug'), 'products', ['slug'], unique=True, schema='store')
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_cart_item_quantity_positive'),
    sa.ForeignKeyConstraint(['cart_id'], ['store.carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_product'),
    schema='store'
    )
    op.create_index(op.f('ix_store_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False, schema='store')
    op.create_index(op.f('ix_store_cart_items_product_id'), 'cart_items', ['product_id'], unique=False, schema='store')
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_quantity_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_order_item_subtotal_positive'),
    sa.CheckConstraint('unit_price > 0', name='ck_order_item_unit_price_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['store.orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store.products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='store')
    op.create_index(op.f('ix_store_order_items_product_id'), 'order_items', ['product_id'], unique=False, schema='store')
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'NET_BANKING', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('gateway_name', sa.String(length=100), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['store.orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_payments_order_id'), 'payments', ['order_id'], unique=True, schema='store')
    op.create_index(op.f('ix_store_payments_public_id'), 'payments', ['public_id'], unique=True, schema='store')
    op.create_index(op.f('ix_store_payments_transaction_reference'), 'payments', ['transaction_reference'], unique=True, schema='store')
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.CheckConstraint('display_order > 0', name='ck_product_image_display_order_positive'),
    sa.CheckConstraint('file_size > 0', name='ck_product_image_file_size_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['store.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename'),
    schema='store'
    )
    op.create_index(op.f('ix_store_product_images_product_id'), 'product_images', ['product_id'], unique=False, schema='store')
    op.create_index(op.f('ix_store_product_images_public_id'), 'product_images', ['public_id'], unique=True, schema='store')
    op.create_index(op.f('ix_store_product_images_sha256_hash'), 'product_images', ['sha256_hash'], unique=False, schema='store')
    op.create_table('product_reviews',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_customer_product_review'),
    schema='store'
    )
    op.create_index(op.f('ix_store_product_reviews_customer_id'), 'product_reviews', ['customer_id'], unique=False, schema='store')
    op.create_index(op.f('ix_store_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False, schema='store')
    op.create_table('wishlist_item',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_customer_product_wishlist'),
    schema='store'
    )
    op.create_index(op.f('ix_store_wishlist_item_customer_id'), 'wishlist_item', ['customer_id'], unique=False, schema='store')
    op.create_index(op.f('ix_store_wishlist_item_product_id'), 'wishlist_item', ['product_id'], unique=False, schema='store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_wishlist_item_product_id'), table_name='wishlist_item', schema='store')
    op.drop_index(op.f('ix_store_wishlist_item_customer_id'), table_name='wishlist_item', schema='store')
    op.drop_table('wishlist_item', schema='store')
    op.drop_index(op.f('ix_store_product_reviews_product_id'), table_name='product_reviews', schema='store')
    op.drop_index(op.f('ix_store_product_reviews_customer_id'), table_name='product_reviews', schema='store')
    op.drop_table('product_reviews', schema='store')
    op.drop_index(op.f('ix_store_product_images_sha256_hash'), table_name='product_images', schema='store')
    op.drop_index(op.f('ix_store_product_images_public_id'), table_name='product_images', schema='store')
    op.drop_index(op.f('ix_store_product_images_product_id'), table_name='product_images', schema='store')
    op.drop_table('product_images', schema='store')
    op.drop_index(op.f('ix_store_payments_transaction_reference'), table_name='payments', schema='store')
    op.drop_index(op.f('ix_store_payments_public_id'), table_name='payments', schema='store')
    op.drop_index(op.f('ix_store_payments_order_id'), table_name='payments', schema='store')
    op.drop_table('payments', schema='store')
    op.drop_index(op.f('ix_store_order_items_product_id'), table_name='order_items', schema='store')
    op.drop_index(op.f('ix_store_order_items_order_id'), table_name='order_items', schema='store')
    op.drop_table('order_items', schema='store')
    op.drop_index(op.f('ix_store_cart_items_product_id'), table_name='cart_items', schema='store')
    op.drop_index(op.f('ix_store_cart_items_cart_id'), table_name='cart_items', schema='store')
    op.drop_table('cart_items', schema='store')
    op.drop_index(op.f('ix_store_products_slug'), table_name='products', schema='store')
    op.drop_index(op.f('ix_store_products_name'), table_name='products', schema='store')
    op.drop_index(op.f('ix_store_products_category_id'), table_name='products', schema='store')
    op.drop_table('products', schema='store')
    op.drop_index(op.f('ix_store_phone_numbers_customer_id'), table_name='phone_numbers', schema='store')
    op.drop_table('phone_numbers', schema='store')
    op.drop_index(op.f('ix_store_orders_public_id'), table_name='orders', schema='store')
    op.drop_index(op.f('ix_store_orders_customer_id'), table_name='orders', schema='store')
    op.drop_table('orders', schema='store')
    op.drop_index(op.f('ix_store_customer_addresses_customer_id'), table_name='customer_addresses', schema='store')
    op.drop_table('customer_addresses', schema='store')
    op.drop_index(op.f('ix_store_carts_customer_id'), table_name='carts', schema='store')
    op.drop_table('carts', schema='store')
    op.drop_index(op.f('ix_store_customers_email'), table_name='customers', schema='store')
    op.drop_table('customers', schema='store')
    op.drop_index(op.f('ix_store_categories_slug'), table_name='categories', schema='store')
    op.drop_table('categories', schema='store')
    # ### end Alembic commands ###
