"""create product images

Revision ID: 69265c61b6d5
Revises: 0da4f97b90eb
Create Date: 2026-06-28 12:42:42.682386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69265c61b6d5'
down_revision: Union[str, Sequence[str], None] = '0da4f97b90eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename'),
    schema='store'
    )
    op.create_index(op.f('ix_store_product_images_product_id'), 'product_images', ['product_id'], unique=False, schema='store')
    op.create_index(op.f('ix_store_product_images_public_id'), 'product_images', ['public_id'], unique=True, schema='store')
    op.create_index(op.f('ix_store_product_images_sha256_hash'), 'product_images', ['sha256_hash'], unique=False, schema='store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_product_images_sha256_hash'), table_name='product_images', schema='store')
    op.drop_index(op.f('ix_store_product_images_public_id'), table_name='product_images', schema='store')
    op.drop_index(op.f('ix_store_product_images_product_id'), table_name='product_images', schema='store')
    op.drop_table('product_images', schema='store')
    # ### end Alembic commands ###
