"""create security schema

Revision ID: 8374c443d137
Revises: 2e59398fc13d
Create Date: 2026-06-29 19:53:51.187065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8374c443d137'
down_revision: Union[str, Sequence[str], None] = '2e59398fc13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_ips',
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('reason', sa.Enum('brute_force', 'credential_stuffing', 'sql_injection', 'xss', 'bot', 'rate_limit', 'manual', 'other', name='block_reason'), nullable=False),
    sa.Column('blocked_by', sa.String(length=100), nullable=False),
    sa.Column('block_note', sa.String(length=500), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permanently_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_blocked_ips_ip_address'), 'blocked_ips', ['ip_address'], unique=True, schema='security')
    op.create_table('audit_logs',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'logout', 'password_change', 'email_change', 'address_change', 'phone_number_change', 'order_placed', 'order_cancelled', 'payment_success', 'payment_failed', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.Enum('customer', 'product', 'category', 'order', 'payment', 'address', 'phone_number', 'review', 'cart', 'wishlist', name='entity_type'), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('entity_public_id', sa.String(length=32), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_audit_logs_customer_id'), 'audit_logs', ['customer_id'], unique=False, schema='security')
    op.create_index(op.f('ix_security_audit_logs_entity_public_id'), 'audit_logs', ['entity_public_id'], unique=False, schema='security')
    op.create_index(op.f('ix_security_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False, schema='security')
    op.create_index(op.f('ix_security_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False, schema='security')
    op.create_table('customer_sessions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('operating_system', sa.String(length=50), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at > login_at', name='ck_customer_session_expiry'),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_customer_sessions_customer_id'), 'customer_sessions', ['customer_id'], unique=False, schema='security')
    op.create_index(op.f('ix_security_customer_sessions_ip_address'), 'customer_sessions', ['ip_address'], unique=False, schema='security')
    op.create_index(op.f('ix_security_customer_sessions_refresh_token_hash'), 'customer_sessions', ['refresh_token_hash'], unique=True, schema='security')
    op.create_table('login_attempts',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('attempt_type', sa.Enum('login', 'register', 'password_reset', 'email_verification', 'refresh_token', 'logout', name='attempt_type'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Enum('invalid_credentials', 'account_locked', 'account_disabled', 'email_not_verified', 'token_expired', 'token_reused', 'rate_limited', 'unknown', name='authentication_failure_reason'), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_login_attempts_customer_id'), 'login_attempts', ['customer_id'], unique=False, schema='security')
    op.create_index(op.f('ix_security_login_attempts_email'), 'login_attempts', ['email'], unique=False, schema='security')
    op.create_index(op.f('ix_security_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False, schema='security')
    op.create_index(op.f('ix_security_login_attempts_request_id'), 'login_attempts', ['request_id'], unique=False, schema='security')
    op.create_table('request_logs',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD', name='http_method'), nullable=False),
    sa.Column('protocol', sa.Enum('HTTP/1.1', 'HTTP/2', 'HTTP/3', name='http_protocol'), nullable=False),
    sa.Column('source', sa.Enum('web', 'mobile', 'api', name='request_source'), nullable=False),
    sa.Column('outcome', sa.Enum('success', 'redirect', 'client_error', 'server_error', name='request_outcome'), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('query_string', sa.String(length=2048), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('request_size', sa.Integer(), nullable=False),
    sa.Column('response_size', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('referer', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['security.customer_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_request_logs_customer_id'), 'request_logs', ['customer_id'], unique=False, schema='security')
    op.create_index(op.f('ix_security_request_logs_ip_address'), 'request_logs', ['ip_address'], unique=False, schema='security')
    op.create_index(op.f('ix_security_request_logs_request_id'), 'request_logs', ['request_id'], unique=True, schema='security')
    op.create_index(op.f('ix_security_request_logs_response_time_ms'), 'request_logs', ['response_time_ms'], unique=False, schema='security')
    op.create_index(op.f('ix_security_request_logs_session_id'), 'request_logs', ['session_id'], unique=False, schema='security')
    op.create_index(op.f('ix_security_request_logs_status_code'), 'request_logs', ['status_code'], unique=False, schema='security')
    op.create_table('security_events',
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('brute_force', 'credential_stuffing', 'sql_injection', 'xss', 'csrf', 'path_traversal', 'rate_limit_exceeded', 'token_reuse', 'invalid_token', 'suspicious_login', 'bot_detected', 'account_locked', 'unknown', name='security_event_type'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='event_severity'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['store.customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['security.customer_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_security_events_customer_id'), 'security_events', ['customer_id'], unique=False, schema='security')
    op.create_index(op.f('ix_security_security_events_ip_address'), 'security_events', ['ip_address'], unique=False, schema='security')
    op.create_index(op.f('ix_security_security_events_request_id'), 'security_events', ['request_id'], unique=False, schema='security')
    op.create_index(op.f('ix_security_security_events_resolved'), 'security_events', ['resolved'], unique=False, schema='security')
    op.create_index(op.f('ix_security_security_events_session_id'), 'security_events', ['session_id'], unique=False, schema='security')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_security_events_session_id'), table_name='security_events', schema='security')
    op.drop_index(op.f('ix_security_security_events_resolved'), table_name='security_events', schema='security')
    op.drop_index(op.f('ix_security_security_events_request_id'), table_name='security_events', schema='security')
    op.drop_index(op.f('ix_security_security_events_ip_address'), table_name='security_events', schema='security')
    op.drop_index(op.f('ix_security_security_events_customer_id'), table_name='security_events', schema='security')
    op.drop_table('security_events', schema='security')
    op.drop_index(op.f('ix_security_request_logs_status_code'), table_name='request_logs', schema='security')
    op.drop_index(op.f('ix_security_request_logs_session_id'), table_name='request_logs', schema='security')
    op.drop_index(op.f('ix_security_request_logs_response_time_ms'), table_name='request_logs', schema='security')
    op.drop_index(op.f('ix_security_request_logs_request_id'), table_name='request_logs', schema='security')
    op.drop_index(op.f('ix_security_request_logs_ip_address'), table_name='request_logs', schema='security')
    op.drop_index(op.f('ix_security_request_logs_customer_id'), table_name='request_logs', schema='security')
    op.drop_table('request_logs', schema='security')
    op.drop_index(op.f('ix_security_login_attempts_request_id'), table_name='login_attempts', schema='security')
    op.drop_index(op.f('ix_security_login_attempts_ip_address'), table_name='login_attempts', schema='security')
    op.drop_index(op.f('ix_security_login_attempts_email'), table_name='login_attempts', schema='security')
    op.drop_index(op.f('ix_security_login_attempts_customer_id'), table_name='login_attempts', schema='security')
    op.drop_table('login_attempts', schema='security')
    op.drop_index(op.f('ix_security_customer_sessions_refresh_token_hash'), table_name='customer_sessions', schema='security')
    op.drop_index(op.f('ix_security_customer_sessions_ip_address'), table_name='customer_sessions', schema='security')
    op.drop_index(op.f('ix_security_customer_sessions_customer_id'), table_name='customer_sessions', schema='security')
    op.drop_table('customer_sessions', schema='security')
    op.drop_index(op.f('ix_security_audit_logs_request_id'), table_name='audit_logs', schema='security')
    op.drop_index(op.f('ix_security_audit_logs_ip_address'), table_name='audit_logs', schema='security')
    op.drop_index(op.f('ix_security_audit_logs_entity_public_id'), table_name='audit_logs', schema='security')
    op.drop_index(op.f('ix_security_audit_logs_customer_id'), table_name='audit_logs', schema='security')
    op.drop_table('audit_logs', schema='security')
    op.drop_index(op.f('ix_security_blocked_ips_ip_address'), table_name='blocked_ips', schema='security')
    op.drop_table('blocked_ips', schema='security')
    # ### end Alembic commands ###
