"""add url to product_images

Revision ID: aec790188470
Revises: cfc77ad6e525
Create Date: 2026-07-05 08:25:41.455842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec790188470'
down_revision: Union[str, Sequence[str], None] = 'cfc77ad6e525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
        op.execute("CREATE SCHEMA IF NOT EXISTS store")
        op.execute("CREATE SCHEMA IF NOT EXISTS security")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('url', sa.String(length=500), nullable=True), schema='store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'url', schema='store')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
