"""make product_image.url required

Revision ID: bbee470b4873
Revises: aec790188470
Create Date: 2026-07-05 11:02:22.990165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbee470b4873'
down_revision: Union[str, Sequence[str], None] = 'aec790188470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               schema='store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               schema='store')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
