"""update_customer_session

Revision ID: cf068cc54d2b
Revises: 8374c443d137
Create Date: 2026-07-02 20:13:50.361777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf068cc54d2b'
down_revision: Union[str, Sequence[str], None] = '8374c443d137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True), schema='security')
    op.alter_column('customer_sessions', 'refresh_token_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False,
               schema='security')
    op.drop_column('customer_sessions', 'revoked', schema='security')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_sessions', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='security')
    op.alter_column('customer_sessions', 'refresh_token_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False,
               schema='security')
    op.drop_column('customer_sessions', 'revoked_at', schema='security')
    # ### end Alembic commands ###
