"""make review_image table

Revision ID: f08a8e655ad6
Revises: bbee470b4873
Create Date: 2026-07-08 19:43:11.659087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08a8e655ad6'
down_revision: Union[str, Sequence[str], None] = 'bbee470b4873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_review_images',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['store.product_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_public_id'),
    schema='store'
    )
    op.create_index(op.f('ix_store_product_review_images_public_id'), 'product_review_images', ['public_id'], unique=True, schema='store')
    op.create_index(op.f('ix_store_product_review_images_review_id'), 'product_review_images', ['review_id'], unique=False, schema='store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_index(op.f('ix_store_product_review_images_review_id'), table_name='product_review_images', schema='store')
    op.drop_index(op.f('ix_store_product_review_images_public_id'), table_name='product_review_images', schema='store')
    op.drop_table('product_review_images', schema='store')
    # ### end Alembic commands ###
