from address_service import AddressService
from cart_service import CartService
from order_service import OrderService
from product_service import ProductService
from phone_service import PhoneService
from category_service import CategoryService
from wishlist_service import WishlistService
from review_service import ReviewService
